name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}